name: validate-project

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
      - run: pip install -r requirements.txt
      - run: python -m src.generate_data
      - run: python -m src.prepare_data
      - run: python -m src.create_assets
      - run: python -m pytest -q

